// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLSuNKYK0EG1r1_2ENztOL8GOi7Y5t-z8',
    appId: '1:466696781902:web:d94254db1dd069351b831f',
    messagingSenderId: '466696781902',
    projectId: 'loginscreen-b0d5a',
    authDomain: 'loginscreen-b0d5a.firebaseapp.com',
    storageBucket: 'loginscreen-b0d5a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWsBZUXuOywSFF9LF4KtQIJ1h0Mhblv8s',
    appId: '1:466696781902:android:43b96b3b8448c29a1b831f',
    messagingSenderId: '466696781902',
    projectId: 'loginscreen-b0d5a',
    storageBucket: 'loginscreen-b0d5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ58gqFeHN6g6OFt6DM_NDiXx61cNMFvY',
    appId: '1:466696781902:ios:91beb85f3447dd581b831f',
    messagingSenderId: '466696781902',
    projectId: 'loginscreen-b0d5a',
    storageBucket: 'loginscreen-b0d5a.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ58gqFeHN6g6OFt6DM_NDiXx61cNMFvY',
    appId: '1:466696781902:ios:91beb85f3447dd581b831f',
    messagingSenderId: '466696781902',
    projectId: 'loginscreen-b0d5a',
    storageBucket: 'loginscreen-b0d5a.appspot.com',
    iosBundleId: 'com.example.loginSignup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLSuNKYK0EG1r1_2ENztOL8GOi7Y5t-z8',
    appId: '1:466696781902:web:fd803273188cf1b61b831f',
    messagingSenderId: '466696781902',
    projectId: 'loginscreen-b0d5a',
    authDomain: 'loginscreen-b0d5a.firebaseapp.com',
    storageBucket: 'loginscreen-b0d5a.appspot.com',
  );
}
